### ISSUE TITLE
Implement data (csv) import and alignment to existing schema

### ISSUE THREAD

**Issue by isTravis** [underlay/underlay.org#43]
On the data tab, users should be able to upload CSVs and align them to an existing schema. 

Aligned data is also processed to apply a UUID to each entity/relationship so that it can be uniquely referenced internally, and consistently even if it's values change over time.

On completion, the uploaded & aligned data becomes a new version.

**Comment by octref** [comment]
- [ ] Transform CSV into a new CSV with UUID for each node before uploading

**Comment by isTravis** [comment]
Addressed in #69.
